version: '3.4'

services:
  app:
    environment:
      PORT: 8000
    restart: always
    container_name: solstice_docs_app
    build:
      context: .
      target: app-container
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
    stdin_open: true
    tty: true
  node-bundler:
    build:
      context: .
      target: node-bundler
    restart: always
    container_name: solstice_docs_node
    ports:
      - "${BUNDLE_ANALYZER_PORT:-8888}:8888" # Required when environment.BUNDLE_ANALYZER is true
    environment:
      VUE_DEVTOOLS: "True"
      BUNDLE_ANALYZER: "True"
    volumes:
      - ./:/app/
      #- ./app_name_vue:/app/app_name_vue
      #- statics-volume:/static
    command: npm run dev
    stdin_open: true
    tty: true
#volumes:
  #statics-volume:
