version: '3.4'

services:
  app:
    restart: always
    container_name: solstice_vite
    build:
      context: .
      target: vite-container
    ports:
      - "8000:5173"
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ./src:/app/src
