autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

ingress:
  enabled: true
  type: nginx
  tls:
    solstice-docs:
      secretName: solstice.uw.edu-ingress-cert
      hosts:
        - solstice.uw.edu
  hosts:
    solstice-docs:
      host: solstice.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

repo: solstice-docs
instance: prod

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 25m
    memory: 128Mi

service:
  enabled: true
  ports:
    - port: 80
      targetPort: 8000
      name: http
    - port: 9113
      targetPort: 9113
      name: metrics

deploymentInitialization:
  enabled: false

daemon:
  enabled: false

database:
  engine: null

externalService:
  enabled: false

cronjob:
  enabled: false

memcached:
  enabled: false

certs:
  mounted: false

gcsCredentials:
  mounted: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    port: metrics

readiness:
  enabled: false

lifecycle:
  enabled: true

environmentVariables:
  - name: "ENV"
    value: "prod"
