autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

ingress:
  enabled: true
  type: nginx
  tls:
    axdd-components:
      secretName: components.axdd.s.uw.edu-ingress-cert
      hosts:
        - components.axdd.s.uw.edu
    axdd-styleguide:
      secretName: styleguide.axdd.s.uw.edu-ingress-cert
      hosts:
        - styleguide.axdd.s.uw.edu
  hosts:
    axdd-components:
      host: components.axdd.s.uw.edu
      paths:
        - "/"
    axdd-styleguide:
      host: styleguide.axdd.s.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host != 'components.axdd.s.uw.edu' ) {
        return 301 $scheme://components.axdd.s.uw.edu;
      }

repo: axdd-components
instance: prod

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 25m
    memory: 128Mi

service:
  enabled: true
  ports:
    - port: 80
      targetPort: 8000
      name: http
    - port: 9113
      targetPort: 9113
      name: metrics

deploymentInitialization:
  enabled: false

daemon:
  enabled: false

database:
  engine: null

externalService:
  enabled: false

cronjob:
  enabled: false

memcached:
  enabled: false

certs:
  mounted: false

gcsCredentials:
  mounted: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    port: metrics

readiness:
  enabled: false

lifecycle:
  enabled: true

environmentVariables:
  - name: "ENV"
    value: "prod"
